version: "3.8"

services:
  app:
    build: .
    container_name: fastapi_app
    image: fastapi_image
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_PORT=${SERVER_PORT}